# ----------------------------------------------------------------------------------------------- #
#
@doc """
	usageCLI(; io::IO = stdout)

Print the command-line usage/help text to `io` (defaults to stdout). 
Used by the CLI when `-h`/`--help` is requested or when no arguments are provided.
"""
function usageCLI(; io::IO = stdout)
	println(io, "# Usage")
	println(io, "  zettel convert <input> <output> [--from <fmt>] --to <fmt>")
	println(io, "  zettel doi     <doi> [--source <name>] [--to <fmt>] [--output <file>] [--mailto <email>] [--plus-token <token>]")
	println(io, "  zettel --query <bibkey> --library <file>")
	println(io, "  zettel bbl     <bblfile> <input.bib> <output.bib>")
	println(io, "  zettel paste   [--to <fmt>] --library <file>")
	println(io, "  zettel paste   --library <file.json>   # paste a BibTeX entry into a JSON library")
	println(io, "  zettel paste   --to <fmt>")
	println(io, "  zettel libupdate --library <file> [--key <key>] [--fileDir <dir>]")
	println(io, "  zettel <auxfile> [options]")
	println(io, "")
	println(io, "# Commands")
	println(io, "  convert        Convert a bibliography file between formats (bib, json, yaml).")
	println(io, "  doi            Fetch a DOI from a metadata source and emit one ZettelEntry (bib, json, yaml).")
	println(io, "  --query        Query one bibkey in a library and print a compact human-readable summary.")
	println(io, "  bbl            Extract the entries cited in a .bbl from a library into a new .bib (used keys only).")
	println(io, "  paste          Read a BibTeX entry from stdin; print it and/or insert it into a library.")
	println(io, "                 The library format follows its extension, so a BibTeX entry pasted into a")
	println(io, "                 .json/.yaml library is converted to JSON/YAML on the way in.")
	println(io, "  libupdate      Read one BibTeX entry from stdin, generate/update key, backup library, and insert it.")
	println(io, "")
	println(io, "# Options (convert)")
	println(io, "  -f, --from <fmt>       Input format (inferred from extension when omitted)")
	println(io, "  -t, --to   <fmt>       Output format (required)")
	println(io, "")
	println(io, "# Options (doi)")
	println(io, "      --source <name>    Metadata source (default: crossref; supported: $(join(doiSources(), ", ")))")
	println(io, "  -t, --to <fmt>         Output format for the fetched entry (bib, json, yaml; default: bib)")
	println(io, "  -o, --output <file>    Write output to file instead of stdout")
	println(io, "  -m, --mailto <email>   Contact email for Crossref polite access (crossref source)")
	println(io, "      --plus-token <tok> Crossref Metadata Plus API token (crossref source, optional)")
	println(io, "")
	println(io, "# Options (--query)")
	println(io, "      --query <bibkey>   Citation key to query in the target library")
	println(io, "  -l, --library <file>   Source library (.bib, .json, .yaml/.yml)")
	println(io, "")
	println(io, "# Options (bbl)")
	println(io, "  <bblfile>              LaTeX .bbl file providing the cited keys")
	println(io, "  <input.bib>            Master library to pull entries from (.bib, .json, .yaml/.yml)")
	println(io, "  <output.bib>           Destination for the extracted subset (format from extension)")
	println(io, "")
	println(io, "# Options (paste)")
	println(io, "  -t, --to   <fmt>       Print the entry in this format to stdout (bib, json, yaml)")
	println(io, "  -l, --library <file>   Insert the entry into this library and rewrite it. The library")
	println(io, "                         format is taken from the file extension (.bib/.json/.yaml), so a")
	println(io, "                         generated key is assigned and the BibTeX entry is converted before insertion.")
	println(io, "")
	println(io, "# Options (libupdate)")
	println(io, "  -l, --library <file>   Target library to update (.bib, .json, .yaml/.yml)")
	println(io, "      --key <key>        Force key instead of generated suggestion")
	println(io, "      --fileDir <dir>    File lookup directory (default: <libraryDir>/files)")
	println(io, "")
	println(io, "# Options (aux mode)")
	println(io, "  -l, --library <file>   Library file (repeatable; inferred from \\bibdata when omitted)")
	println(io, "  -o, --output <file>    Output .bbl path (default: <auxfile>.bbl)")
	println(io, "  -s, --style <name>     Bibliography style (default: auto)")
	println(io, "")
	println(io, "  -h, --help             Show this message")
end


# ----------------------------------------------------------------------------------------------- #
#