module Zettel

using Downloads
using JSON3
using Pybtex
using PythonCall: pyconvert

export fetchCrossrefJson, saveCrossrefJson, bibTeXToJson, jsonToBibTeX

const crossrefBaseUrl = "https://api.crossref.org/works/"

@doc """
Fetch metadata for a DOI from Crossref and return it as a JSON dictionary.
"""
function fetchCrossrefJson(doi::AbstractString; fetcher::Function = defaultFetcher)
	escapedDoi = encodeUriComponent(String(doi))
	payload = fetcher("$(crossrefBaseUrl)$(escapedDoi)")
	parsed = try
		JSON3.read(payload)
	catch
		throw(ArgumentError("Crossref response was not valid JSON."))
	end
	if haskey(parsed, :message)
		return toPlainDict(parsed[:message])
	end
	throw(ArgumentError("Crossref response did not contain a message field."))
end

@doc """
Fetch metadata for a DOI from Crossref and save it to `outputPath`.
"""
function saveCrossrefJson(doi::AbstractString, outputPath::AbstractString; fetcher::Function = defaultFetcher)
	record = fetchCrossrefJson(doi; fetcher = fetcher)
	write(outputPath, JSON3.write(record))
	return outputPath
end

@doc """
Convert a BibTeX file into JSON while preserving entry type, fields, and persons.
"""
function bibTeXToJson(inputPath::AbstractString, outputPath::AbstractString)
	isfile(inputPath) || throw(ArgumentError("Input BibTeX file not found: $(inputPath)"))
	library = readBibtexDataBase(String(inputPath))
	entries = Dict{String, Any}()

	for key in keys(library)
		entry = getEntry(library, key)
		fields = Dict{String, String}()
		for field in getAllFields(entry)
			fields[String(field)] = pyconvert(String, entry.info.fields[field])
		end

		persons = Dict{String, Vector{String}}()
		for role in pyconvert(Vector{String}, entry.info.persons.keys())
			names = String[]
			for person in entry.info.persons[role]
				push!(names, pyconvert(String, person.__str__()))
			end
			persons[role] = names
		end

		entries[String(key)] = Dict(
			"entryType" => lowercase(getType(entry)),
			"fields" => fields,
			"persons" => persons,
		)
	end

	data = Dict("entries" => entries)
	write(outputPath, JSON3.write(data))
	return outputPath
end

@doc """
Convert a JSON bibliography generated by `bibTeXToJson` back into BibTeX via Pybtex.jl.
"""
function jsonToBibTeX(inputPath::AbstractString, outputPath::AbstractString)
	isfile(inputPath) || throw(ArgumentError("Input JSON file not found: $(inputPath)"))
	parsed = try
		JSON3.read(read(inputPath, String))
	catch
		throw(ArgumentError("Input JSON file is not valid JSON: $(inputPath)"))
	end
	entries = parsed[:entries]

	io = IOBuffer()
	for (rawKey, rawEntry) in pairs(entries)
		key = String(rawKey)
		entryType = String(rawEntry[:entryType])
		println(io, "@$(entryType){$(key),")

		if haskey(rawEntry, :persons)
			for (rawRole, rawNames) in pairs(rawEntry[:persons])
				role = String(rawRole)
				names = [String(name) for name in rawNames]
				if !isempty(names)
					personLine = join(names, " and ")
					println(io, "\t$(role) = {$(personLine)},")
				end
			end
		end

		for (rawField, rawValue) in pairs(rawEntry[:fields])
			field = String(rawField)
			value = String(rawValue)
			println(io, "\t$(field) = {$(value)},")
		end

		println(io, "}\n")
	end

	(tempPath, handle) = mktemp()
	try
		write(handle, String(take!(io)))
		close(handle)
		library = readBibtexDataBase(tempPath)
		writeBibtexDataBase(library, String(outputPath))
	finally
		isopen(handle) && close(handle)
		rm(tempPath; force = true)
	end

	return outputPath
end

function defaultFetcher(url::AbstractString)
	tmpFile = Downloads.download(url)
	try
		return read(tmpFile, String)
	finally
		rm(tmpFile; force = true)
	end
end

function toPlainDict(node)
	if node isa Dict
		return Dict(String(k) => toPlainDict(v) for (k, v) in node)
	elseif node isa AbstractVector
		return [toPlainDict(v) for v in node]
	elseif node isa JSON3.Object
		return Dict(String(k) => toPlainDict(v) for (k, v) in pairs(node))
	elseif node isa JSON3.Array
		return [toPlainDict(v) for v in node]
	else
		return node
	end
end

function encodeUriComponent(value::AbstractString)
	io = IOBuffer()
	for b in codeunits(value)
		if isAsciiUnreserved(b)
			write(io, b)
		else
			print(io, '%')
			print(io, uppercase(string(b, base = 16, pad = 2)))
		end
	end
	return String(take!(io))
end

function isAsciiUnreserved(b::UInt8)
	return (UInt8('A') <= b <= UInt8('Z')) ||
		(UInt8('a') <= b <= UInt8('z')) ||
		(UInt8('0') <= b <= UInt8('9')) ||
		b == UInt8('-') ||
		b == UInt8('.') ||
		b == UInt8('_') ||
		b == UInt8('~')
end

end
export
	ZettelEntry,
	ZettelLibrary,
	readJsonLibrary,
	writeJsonLibrary,
	readBibTeX,
	writeBibTeX,
	toBibTeX,
	fromBibTeX,
	fetchFromCrossref,
	getKey,
	getType,
	getField,
	hasField,
	getAuthors,
	getTitle,
	getYear,
	getJournal,
	getDOI,
	getURL,
	getVolume,
	getNumber,
	getPages,
	getAbstract,
	getPublisher,
	getISBN,
	getAllFields

using HTTP
using JSON3
using OrderedCollections
using Printf
using PythonCall
using Pybtex


include("types.jl")
include("json_io.jl")
include("crossref.jl")
include("bibtex.jl")


end # module Zettel
